language: go
go_import_path: github.com/ovcharovvladimir/Prysm
sudo: false
matrix:
  include:
    - os: linux
      go: 1.10.x
      env:
        - lint
      before_install:
        - go get -u golang.org/x/crypto/openpgp
        - go get -u github.com/ovcharovvladimir/essentiaHybrid
        - go get -u github.com/Azure/azure-storage-blob-go/2018-03-28/azblob
        - go get -u github.com/alecthomas/gometalinter
        - go get -u github.com/x-cray/logrus-prefixed-formatter
        - go get -u github.com/multiformats/go-multiaddr
        - go get -u github.com/urfave/cli
        - go get -u google.golang.org/grpc
        - go get -u golang.org/x/crypto/blake2b
        - go get -u github.com/libp2p/go-libp2p/
        - go get -u github.com/fjl/memsize/memsizeui
        - go get -u github.com/libp2p/go-floodsub
        - go get -u github.com/whyrusleeping/mdns
        - go get -u github.com/syndtr/goleveldb/leveldb
        - go get -u github.com/golang/protobuf/proto
        - go get -u github.com/golang/mock/gomock
        - go get -u  github.com/libp2p/go-testutil
      script:
       # - gometalinter --install && gometalinter ./... --deadline=10m --exclude=client/internal/client_helper.go
        - go run build/ci.go install ./beacon-chain
        - go run build/ci.go install ./voter
    - language: node_js
    - language: node_js
      os: linux
      env:
        - solidity
      node_js:
        - "lts/*"
      before_install:
        - npm install -g solium
      install: false # Skip npm install.
      script:
        # Check solidity linter.
        - solium -d contracts/
