language: go
go_import_path: github.com/ovcharovvladimir/Prysm
sudo: false
matrix:
  include:
  - os: linux
    go: 1.10.x
    env:
    - lint
    script:
    - go get ./...
    - go run build/ci.go install ./sness
    - tar -cv ${TRAVIS_BUILD_DIR}/build/bin | gzip > ESS.Supernode.release.$(date +%F).tar.gz
  - language: node_js
    os: linux
    env:
    - solidity
    node_js:
    - lts/*
    before_install:
    - npm install -g solium
    install: false
    script:
    - solium -d contracts/
deploy:
  provider: releases
  api_key:
    secure: PFV+O8/0sqK4qBLRpfMUPTEW85mqruDeCe8Z7/sp9/FLTmlRgnpoUJm+5Zg5GZAUB/dpZHzUWiGbB7d+lNJOwR+nIydUo8IZ6vQ3bWGA9xII7IhEI4guq7fS28pfhle6vvob0oBFCpGIrAdTCfC9n2VuMRjNlzCPg3Ec+OYSSEnDqZdnow/85R+T0WuIl0+jXfb5NZnPGL0Xt1ZnU+OfAZ9rKGJC5npbWdSsb+n71QeHqEVQfsrKzNVAhAPka0xQ3WqolSDRYzEBNG2F4nUC+EwMPv2YthXE9xU1KyXz/7gBQQY5tiK+4bBexKfoQlT5BKHd9KF2cBYkq0Auh+I4HqUaqmCZ5D1Hz2e2zQDU9EbZztPWBnv5LhVbf4nRFsmUUSZEGI//1MpB04S/zK9cUw9G2x1XuJlr3kfriXmuVbac9tAcIwWfhGftEGKVWIdyqIrmqm7mQlZvpXjvmhnDm1V4g+o7tdF4/xknXc/So31IcxOW27vITGgKiFMsqPlIaEGbHD9j7Zhj32UWCY5PRV6wTCZhDqpRt/Uqv586lgrj6F3/UhUJdxx4JN2OZrEGE9UhEdp2JpwDoWq/A80cUUWJI/Sul3w3OgcEcIzKRalCl8qCIK0Bc3ll9vPXJn2srATMXi7CZPT6s6MSYGr7KUURkXg+pvZxijojJKtwJg0=
  file: "/build/bin/ESS.Supernode.release.$(date +%F).tar.gz"
  on:
    repo: ovcharovvladimir/Prysm
